on:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run "make"
        run: make && make static

      - name: Create archive of "build"
        run: tar -czf build.tar.gz build

      - name: Upload build to GitHub release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GHACTIONS_TOKEN }}
          automatic_release_tag: latest
          prerelease: false
          title: CI/CD Build
          files: |
            build.tar.gz
