on:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run "make"
        run: make && make static

      # - name: Create archive of "build"
      #   run: tar -czf build.tar.gz build
